language: "python"

python:
    - "3.7"
    - "3.8"

install:
    - "pip install -U flake8 mypy numpy scipy pandas typing_extensions pytest pytest-cov \"attrs>=19.2.0\" hypothesis coveralls sphinx sphinx_rtd_theme"
    - "pip install -U git+https://github.com/numpy/numpy-stubs.git"
    - "pip install ."

script:
    - 'flake8 tafra'
    - "mypy tafra"
    - "pytest --cov=tafra --cov-report=term-missing --hypothesis-show-statistics -v test"
    - "sphinx-build -W -b html docs docs/_build/html"

notifications:
    - email: false

after_success:
    - "coveralls"
